### ISSUE TITLE
MetaAnchor

### ISSUE THREAD

**Issue by KevenLee** [yangsenius/yangsenius.github.io#1]
Hi, 请问下，你的这篇博客里面的 metaAnchor 你有没有复现？有相关代码否？是否开源？
https://yangsenius.github.io/blog/MetaAnchor/

**Comment by yangsenius** [comment]
不好意思，目前本人没有时间复现这篇论文，主要因为我不做目标检测相关研究。另外，我更新了一些内容在https://blog.csdn.net/senius/article/details/84992294
